# PUT http://localhost:3001/api/notes/1 
# Content-Type: application/json 

# {

# "important": "false"


# }
###
GET http://localhost:3001/api/notes/

###
post http://localhost:3001/api/notes/
Content-Type: application/json

  {
   
    "content": "posting new note",
    "important": true,
    "date": null
  }

###

put http://localhost:3001/api/notes/1
Content-Type: application/json

  {

    "important": false
  
  }
