PUT http://localhost:3001/api/users/second 
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRoaXJkIiwiaWQiOjMsImlhdCI6MTY2MjgyNzg2NX0.Tu50Pt51a57Don8HQyN5Xwvhv0g-mS1bvZkn9RjjcCc

{

"disabled": "true"


}
###
GET http://localhost:3001/api/users/

###
post http://localhost:3001/api/notes/
Content-Type: application/json

  {
   
    "content": "posting new note",
    "important": true,
    "date": null
  }

###

put http://localhost:3001/api/notes/1
Content-Type: application/json

  {

    "important": false
  
  }


###

###
post http://localhost:3001/api/users
content-type:application/json

{
    "username": "second",
    "name": "bravo",
    "password": "secret",
    "disabled":true
}
###
post http://localhost:3001/api/login
content-type:application/json

{
    "username": "third",
    "password": "secret"
}
###
post http://localhost:3001/api/notes
content-type:application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRoaXJkIiwiaWQiOjEsImlhdCI6MTY2Mjg2ODgyN30.XkbhpLmk2rOejjYVn897p1EVac5e4XNxlINw7ktibRs

{
"content":"note 2 by third",
"important":"false"
}